version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gaterun_postgres
    environment:
      - POSTGRES_DB=${PG_DATABASE:-gaterun}
      - POSTGRES_USER=${PG_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-pass1234}
    ports:
      - "5432:5432"
    networks:
      - gaterun_network
    volumes:
      - gaterun_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: gaterun_redis
    ports:
      - "6379:6379"
    networks:
      - redis_network
    volumes:
      - redis_data:/data

networks:
  gaterun_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  gaterun_data:
    driver: local
  redis_data:
    driver: local

  # cassandra:
  #   image: cassandra:latest
  #   container_name: gaterun_cassandra
  #   ports:
  #     - 9042:9042
  #   volumes:
  #     - ./data/cassandra:/var/lib/cassandra
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=cloudinfra
